#!/usr/bin/env node
/**
 * The generated half of the documentation set (T13.5, Draft 2.18).
 *
 *   node scripts/docs.mjs            # writes docs/reference/generated/**
 *   node scripts/docs.mjs --check    # exits 1 if the committed pages are stale
 *
 * Four things are generated rather than written, so they cannot drift from the
 * code: the CLI reference from the CLI's own help, the exports of every
 * published package from its TypeScript entry point, the JSON Schemas from the
 * files `@svatah/yam-schema` ships, and the HTTP API from the service's OpenAPI
 * description. Everything else under `docs/` is written by hand.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "reference", "generated");
const check = process.argv.includes("--check");
const HEADER = "<!-- Generated by `node scripts/docs.mjs`; do not edit. `pnpm docs` regenerates it. -->\n\n";

/** The pages, path → markdown. */
const pages = new Map();
const page = (path, body) => pages.set(path, HEADER + body.trimEnd() + "\n");

/* ── 1. the CLI, from its own help ───────────────────────────────────────── */

// From the built package (T14.3, T14.6): the top-level help, every command's
// own help, and the topics, so the page is what `yam help` prints.
const cliPackage = await import(pathToFileURL(join(ROOT, "packages", "cli", "dist", "index.js")).href);
const fence = (text) => `\`\`\`text\n${text.trimEnd()}\n\`\`\``;
page(
  "cli.md",
  `# \`yam\` command line\n\nWhat \`yam help\` prints, then every command's own \`--help\`, then the help topics. \`yam\` alone prints where you are and what is next. Every command that takes \`--json\` prints one JSON document and nothing else on stdout.\n\n` +
    `## \`yam help\`\n\n${fence(cliPackage.TOP_LEVEL)}\n\n` +
    `## Commands\n\n` +
    cliPackage.COMMANDS.map((one) => `### \`yam ${one.name}\`\n\n${fence(cliPackage.helpFor(one.name.split(" ")) ?? "")}\n`).join("\n") +
    `\n## Topics\n\n` +
    cliPackage.TOPICS.map((name) => `### \`yam help ${name}\`\n\n${fence(cliPackage.topic(name) ?? "")}\n`).join("\n"),
);

/* ── 2. every published package's exports, from its entry point ──────────── */

const packageDirs = readdirSync(join(ROOT, "packages")).filter((dir) =>
  existsSync(join(ROOT, "packages", dir, "package.json")),
);
const entries = packageDirs.map((dir) => {
  const ts_ = join(ROOT, "packages", dir, "src", "index.ts");
  return [dir, existsSync(ts_) ? ts_ : join(ROOT, "packages", dir, "src", "index.tsx")];
});
const program = ts.createProgram(
  entries.map(([, file]) => file),
  {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    jsx: ts.JsxEmit.ReactJSX,
    strict: true,
    skipLibCheck: true,
    noEmit: true,
  },
);
const checker = program.getTypeChecker();

/** One line per export: its kind and the declaration's first line. */
function exportsOf(file) {
  const source = program.getSourceFile(file);
  if (source === undefined) throw new Error(`no source for ${file}`);
  const symbol = checker.getSymbolAtLocation(source);
  if (symbol === undefined) return [];
  const rows = [];
  for (const exported of checker.getExportsOfModule(symbol)) {
    const resolved = exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;
    const declaration = resolved.declarations?.[0];
    if (declaration === undefined) continue;
    const kind = ts.SyntaxKind[declaration.kind]
      .replace("Declaration", "")
      .replace("VariableDeclaration", "const")
      .toLowerCase();
    const text = declaration
      .getText()
      .replace(/\/\*\*[\s\S]*?\*\/\s*/g, "")
      .split("\n")
      .map((line) => line.trim())
      .filter((line) => line !== "")
      .slice(0, 1)[0]
      ?.replace(/\s*\{\s*$/, "")
      .replace(/=\s*$/, "")
      .slice(0, 160);
    const doc = ts.displayPartsToString(resolved.getDocumentationComment(checker)).split("\n")[0]?.trim() ?? "";
    rows.push({ name: exported.getName(), kind, text: text ?? "", doc });
  }
  return rows.sort((a, b) => a.name.localeCompare(b.name));
}

const packagePages = [];
for (const [dir, file] of entries) {
  const manifest = JSON.parse(readFileSync(join(ROOT, "packages", dir, "package.json"), "utf8"));
  const rows = exportsOf(file);
  const table = rows.length
    ? "| Export | Kind | Signature | |\n|---|---|---|---|\n" +
      rows
        .map((r) => `| \`${r.name}\` | ${r.kind} | \`${r.text.replace(/\|/g, "\\|")}\` | ${r.doc.replace(/\|/g, "\\|")} |`)
        .join("\n")
    : "_This package has no public exports; it is a bin or a fixture package._";
  const body =
    `# \`${manifest.name}\`\n\n${manifest.description ?? ""}\n\n` +
    `- Source: [\`packages/${dir}\`](../../../../packages/${dir}) · README: [\`packages/${dir}/README.md\`](../../../../packages/${dir}/README.md)\n` +
    `- Install: \`npm install ${manifest.name}\`${manifest.bin ? ` · bin: ${Object.keys(manifest.bin).map((b) => `\`${b}\``).join(", ")}` : ""}\n` +
    `- Version ${manifest.version} · ${manifest.license}${manifest.private ? " · not published" : ""}\n\n` +
    `## Exports\n\n${table}\n`;
  page(`packages/${dir}.md`, body);
  packagePages.push([manifest.name, dir, manifest.description ?? "", rows.length]);
}
page(
  "packages/README.md",
  "# Packages\n\nOne page per workspace package, generated from its entry point. `@svatah/yam` is the command line; every other package is `@svatah/yam-<name>`.\n\n| Package | Exports | What it is |\n|---|---|---|\n" +
    packagePages
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([name, dir, description, n]) => `| [\`${name}\`](${dir}.md) | ${n} | ${description.replace(/\|/g, "\\|")} |`)
      .join("\n") +
    "\n",
);

/* ── 3. the JSON Schemas @svatah/yam-schema ships ────────────────────────── */

const schemaDir = join(ROOT, "packages", "schema", "json");
const schemaRows = [];
for (const file of readdirSync(schemaDir).filter((f) => f.endsWith(".schema.json")).sort()) {
  const doc = JSON.parse(readFileSync(join(schemaDir, file), "utf8"));
  const rootName = typeof doc.$ref === "string" ? doc.$ref.replace("#/definitions/", "") : undefined;
  const root = rootName !== undefined ? doc.definitions?.[rootName] : doc;
  const required = new Set(root?.required ?? []);
  const props = Object.entries(root?.properties ?? {});
  const kind = (p) => {
    if (p.$ref) return "`" + String(p.$ref).replace("#/definitions/", "") + "`";
    if (p.enum) return p.enum.map((e) => "`" + JSON.stringify(e) + "`").join(" \\| ");
    if (p.type === "array") return `array of ${p.items?.$ref ? "`" + String(p.items.$ref).replace("#/definitions/", "") + "`" : p.items?.type ?? "…"}`;
    if (p.anyOf || p.oneOf) return "one of " + (p.anyOf ?? p.oneOf).length + " shapes";
    return p.type ?? "…";
  };
  const body =
    `# \`${file}\`\n\n- \`$id\`: \`${doc.$id}\`\n- Root: \`${rootName ?? "(inline)"}\` · definitions: ${Object.keys(doc.definitions ?? {}).length}\n\n` +
    (props.length
      ? "## Root properties\n\n| Property | Type | Required |\n|---|---|---|\n" +
        props.map(([name, p]) => `| \`${name}\` | ${kind(p)} | ${required.has(name) ? "yes" : ""} |`).join("\n")
      : "_The root is not an object; see the file._") +
    `\n\nThe file itself: [\`packages/schema/json/${file}\`](../../../../packages/schema/json/${file}).\n`;
  page(`schemas/${file.replace(".schema.json", "")}.md`, body);
  schemaRows.push([file, doc.$id, rootName, props.length]);
}
page(
  "schemas/README.md",
  "# JSON Schemas\n\nThe published contract (REQ-STD-1), generated by `@svatah/yam-schema` from its Zod definitions and shipped under `json/`. A foreign runtime is held to `ir`, `results` and `summary` (LLD §14).\n\n| File | `$id` | Root | Properties |\n|---|---|---|---|\n" +
    schemaRows.map(([f, id, root, n]) => `| [\`${f}\`](${f.replace(".schema.json", "")}.md) | \`${id}\` | \`${root ?? ""}\` | ${n} |`).join("\n") +
    "\n",
);

/* ── 4. the HTTP service, from its OpenAPI description ───────────────────── */

const service = await import(pathToFileURL(join(ROOT, "packages", "service", "dist", "index.js")).href);
const version = JSON.parse(readFileSync(join(ROOT, "packages", "service", "package.json"), "utf8")).version;
const api = service.openApiDocument(version);
const routes = [];
for (const [path, methods] of Object.entries(api.paths ?? {})) {
  for (const [method, op] of Object.entries(methods)) {
    routes.push([method.toUpperCase(), path, op.summary ?? op.description ?? "", op.operationId ?? ""]);
  }
}
page(
  "http-api.md",
  `# Local service HTTP API\n\n${api.info?.description ?? ""}\n\nOpenAPI ${api.openapi}, service version ${version}. The document itself is \`openApiDocument()\` in \`@svatah/yam-service\`; the Python and Java clients under \`clients/\` and \`@svatah/yam-sdk\` are generated from it.\n\n| Method | Path | Summary |\n|---|---|---|\n` +
    routes.map(([m, p, s]) => `| \`${m}\` | \`${p}\` | ${String(s).split("\n")[0].replace(/\|/g, "\\|")} |`).join("\n") +
    "\n",
);

/* ── 5. the support matrix, from the coverage report ─────────────────────── */

/*
 * **Derived, never written** (T20, SF-09, SF-21).
 *
 * The support matrix is the one page in this documentation set a reader makes a
 * decision on: it is where they find out whether Yam can drive the thing in
 * front of them. A matrix somebody typed is a matrix that says what was hoped
 * for on the day it was typed.
 *
 * So this page is generated from `coverage.json`, which
 * `scripts/coverage-report.mjs` generates from runs. `pnpm docs --check` is in
 * the gate, so a coverage report that moves and a matrix that does not is a red
 * build rather than a page that quietly rots.
 */
const coveragePath = join(ROOT, "docs", "spec", "surface-first", "evidence", "wave-4", "coverage.json");
if (existsSync(coveragePath)) {
  const coverage = JSON.parse(readFileSync(coveragePath, "utf8"));
  const STATUS = {
    validated: "**validated**",
    unvalidated: "implemented, unvalidated here",
    blocked: "not available on this host",
  };
  const bar = (text) => String(text ?? "—").replace(/\|/g, "\\|");
  const lines = [
    "# Support matrix",
    "",
    "**Generated. Do not edit.** `node scripts/docs.mjs` derives this page from",
    "`docs/spec/surface-first/evidence/wave-4/coverage.json`, which",
    "`node scripts/coverage-report.mjs` derives from runs. Nothing here is a plan.",
    "",
    `Last measured ${coverage.ranAt} on **${coverage.host.reference}**.`,
    "",
    "## What each word claims",
    "",
    "| Word | What it claims |",
    "|---|---|",
    "| **validated** | A session was opened through this adapter, and driven, in the run this page comes from. |",
    "| implemented, unvalidated here | The adapter is built and registered, and nothing in that run drove it. The reason is given. It is not a claim that it works, and not a claim that it does not. |",
    "| not available on this host | It could not be asked. The reason is the product's own sentence. |",
    "| unimplemented | Absent, with no row below. Linux AT-SPI and process/terminal surfaces are unimplemented. |",
    "",
    "## Adapters",
    "",
    "| Adapter | Platforms | Status | Evidence, or the reason |",
    "|---|---|---|---|",
    ...coverage.adapters.map(
      (one) =>
        `| \`${one.adapter}\` | ${bar(one.platforms)} | ${STATUS[one.status] ?? one.status} | ${bar(one.reason)} |`,
    ),
    "",
    "## Interfaces",
    "",
    "One journey, run through each. The counts are checks passed and reached beside",
    "what was attempted, so a platform that could not be asked is visible rather",
    "than absent (SF-21).",
    "",
    "| Interface | Platform | Passed | Reached | Blocked | Attempted |",
    "|---|---|---|---|---|---|",
    ...coverage.rows
      .filter((one) => one.interface !== "adapter")
      .map(
        (one) =>
          `| ${one.interface} | ${bar(one.platform)} | ${one.passed} | ${one.reached} | ${one.blocked} | ${one.attempted} |`,
      ),
    "",
    "## Timing, on the machine above",
    "",
    "Proposed budgets being calibrated, not a promise. Every sample is a fresh",
    "process, so cold start is included.",
    "",
    "| What | Budget | p95 | Samples |",
    "|---|---|---|---|",
    ...coverage.budgets.map(
      (one) =>
        `| ${one.what} | ${one.budgetMs} ms | ${one.p95Ms === undefined ? "not measured" : `${one.p95Ms} ms`} | ${one.samples} |`,
    ),
    "",
  ];
  page("support-matrix.md", `${lines.join("\n")}`);
}

/* ── write, or check ─────────────────────────────────────────────────────── */

const stale = [];
for (const [path, body] of pages) {
  const target = join(OUT, path);
  if (check) {
    if (!existsSync(target) || readFileSync(target, "utf8") !== body) stale.push(relative(ROOT, target));
  } else {
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, body);
  }
}
if (check) {
  // And nothing committed that is no longer generated.
  const walk = (dir) =>
    readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]));
  if (existsSync(OUT)) {
    for (const file of walk(OUT)) {
      if (!pages.has(relative(OUT, file).split("\\").join("/"))) stale.push(`${relative(ROOT, file)} (no longer generated)`);
    }
  }
  if (stale.length > 0) {
    console.error(`docs are stale:\n  ${stale.join("\n  ")}\nRun \`pnpm docs\`.`);
    process.exit(1);
  }
  console.log(`docs/reference/generated is current (${pages.size} pages).`);
} else {
  if (existsSync(OUT)) {
    // Remove pages that are no longer generated.
    const walk = (dir) =>
      readdirSync(dir, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)]));
    for (const file of walk(OUT)) if (!pages.has(relative(OUT, file).split("\\").join("/"))) rmSync(file);
  }
  console.log(`wrote ${pages.size} pages to docs/reference/generated`);
}
